swagger: "2.0"
info:
  title: Cloud Endpoint + Cloud Run
  description: Storage Service API
  version: 1.0.0
host: storage-api-gh6esglzca-uk.a.run.app
schemes:
  - https
produces:
  - application/json
x-google-backend:
  address: https://storage-svc-gh6esglzca-uk.a.run.app
  protocol: h2
securityDefinitions:
  google_id_token:
    authorizationUrl: ""
    flow: implicit
    type: oauth2
    x-google-issuer: accounts.google.com
    x-google-jwks-uri: https://www.googleapis.com/oauth2/v3/certs
    x-google-audiences: 238885920113-0qcd581pstk7jvgfi25roqmvo98to97b.apps.googleusercontent.com
paths:
  /version:
    get:
      security:
        - google_id_token: []
      operationId: version
      summary: Gets the build version of the storage service.
      responses:
        '200':
          description: Returns the version `v0.0.0`
          schema:
            type: string
  /upload:
    post:
      security:
        - google_id_token: []
      operationId: upload
      summary: This uploads a document(s) to cloud storage.
      consumes:
        - multipart/form-data
      parameters:
        - in: formData
          name: "upload[]"
          type: array
          items:
            type: string
            format: binary
      responses:
        '200':
          description: Returns status code, uid, and uploaded documents
          schema:
            type: string


